embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9
reg_weight: [0.0]

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

dropout: 0
mm_image_weight: 0.1
n_hid : [2000]
omega: [4] #5
steps: [5]
noise_scale: [0.01] # [0.01,0.002]
noise_min: 0.0001
noise_max: [0.02] #[0.02,0.05]
tau: [0.2] #0.2,0.1
weight_cl: [1e-1] #1e-1,
hyper_parameters: ["n_hid", "omega","steps","noise_scale","noise_max","tau","weight_cl"]














